### PR TITLE
Use captureTab() for thumbnails

### PR DESCRIPTION
**Pull request by nyordanov**

### CODE REVIEW

**Comment by photodiode** [comment]
I can't add `captureTab()` in until v59 comes around, sorry.
I don't want to break things for people on v58.

**Comment by nyordanov** [comment]
You can keep the old (0.6.20) version on AMO and just mark the new version as compatible with Firefox 59+ only. 58 users will be stuck on 0.6.20 until they update.

How many users are on 58 anyway?

**Comment by photodiode** [comment]
I might put it in as a complementary thing until 59 lands.
```
Stats for Thu, Feb 8, 2018
v57: 22
v58: 178
v59: 66
v60: 34
```

**Comment by PrototypeNM1** [comment]
Shouldn't it be possible to have parallel implementations running in code, similar to how tab hiding works if available?

**Pull request closed without merging**
